### ISSUE TITLE
Release notes and target platform for v4.32 mention wrong version of Java VM

### ISSUE THREAD

**Issue by habbit-baggins** [eclipse-platform/www.eclipse.org-eclipse#186]
The [release notes for Eclipse 4.32](https://eclipse.dev/eclipse/development/readme_eclipse_4.32.php#mozTocId315234) page has two issues:
* The link to the target platform page is wrong; it goes to the 4.31 version of the page ([link](https://www.eclipse.org/projects/project-plan.php?planurl=https://www.eclipse.org/eclipse/development/plans/eclipse_project_plan_4_31.xml#target_environments)) instead of the correct one ([link](https://www.eclipse.org/projects/project-plan.php?planurl=https://www.eclipse.org/eclipse/development/plans/eclipse_project_plan_4_32.xml#target_environments))
* It mentions the SDK requiring Java 17. The same happens in the target platform page itself, where both v17 and v21 are mentioned as validated platforms.
  > In general, the 4.32 release of the Eclipse Project is developed on Java SE 17 VMs. As such, the Eclipse SDK as a whole is targeted at all modern, desktop Java VMs.

  However, the IDE itself has been popping up a dire warning recently, both before and after the upgrade, saying it absolutely *needs* Java 21 and that using Java 17 may fail to run ([ref](https://www.eclipse.org/setups/sponsor/?scope=Eclipse%20IDE%20for%20RCP%20and%20RAP%20Developers%20(includes%20Incubating%20components)&version=4.31.0.20240307-1200&campaign=2024-06)).

  >  The June 12th release of the Eclipse IDE 2024-06 - 4.32 *requires Java 21*. (...) Depending on how you installed your Eclipse IDE, the following might happen when you update: (...) The IDE will install all available updates but then fail to start: 

Even if the information is _technically correct_, in the sense that parts of the Eclipse SDK could run under Java 17 but the overall IDE product cannot; it is confusing for the user to be told these contradicting pieces of information. Furthermore, the release notes page mentions a nonexisting appendix that is supposed to clarify the issue:
> Appendix 1 contains a table that indicates the class library level required for each bundle.

From the issue template:
- [x] I verified I can reproduce this issue against the current Eclipse website
- [x] I understand reporting an issue to this OSS project does not mandate anyone to fix it. Other contributors may consider the issue, or not, at their own convenience. The most efficient way to get it fixed is that I fix it myself and contribute it back as a good quality patch to the project.

**Comment by merks** [comment]
See this for what requires Java 21:

**Comment by habbit-baggins** [comment]
Okay, so regarding Java 17 vs 21, the conclusion is that nothing in the Eclipse _platform_ (as in RCP components, the launcher, SWT, etc.) requires Java 21, but some components of the _IDE_ do, right? I have no qualms with that, although I would like the difference to be made explicit in the release notes. In particular, there is this paragraph lower down that states:
> As shown [above](https://eclipse.dev/eclipse/development/readme_eclipse_4.32.php#TargetOperatingEnvironments), Eclipse 4.32 requires at least a Java SE 17. Perhaps an older version of the VM is being found in your path. To explicitly specify which VM to run with, use the Eclipse -vm command-line argument. (See also the [Running Eclipse](https://eclipse.dev/eclipse/development/readme_eclipse_4.32.php#RunningEclipse) section below.)

Even if the platform does support Java 17, this text is _not_ true as written - "Eclipse" the IDE _will_ not start with a Java 17 VM without finagling, and even then it will start with some issues.

I also looked at the page more in depth and found other issues. For example, in **three different paragraphs** in the "Compatibility with Previous Releases" section, the link to the "Eclipse 4.32 Plug-in Migration Guide" is also pointing to the 4.31 version. However, the correction in this case is not as trivial, because the 4.32 version of the page does not exist... and neither does the version for 4.31, 4.30, etc. The last version that does exist is [for 4.24](https://eclipse.dev/eclipse/development/porting/eclipse_4_24_porting_guide.html), and indeed the repository does not contain any versions past that. What should be done in this case? Do I just remove the entire "compatibility" section in my fix proposal?
