### ISSUE TITLE
Missing Eclipse Project Plan 4.26 for 2022-12

### ISSUE THREAD

**Issue by pstric** [eclipse-platform/www.eclipse.org-eclipse#19]
The Eclipse Project Plan seems to be missing for 4.26.

On this page https://download.eclipse.org/eclipse/downloads/drops4/S-4.26M1-202209281800/ the link to Eclipse Project Plan points to https://www.eclipse.org/projects/project-plan.php?planurl=https://www.eclipse.org/eclipse/development/plans/eclipse_project_plan_4_26.xml.

Usually this would resolve to a page similar to https://www.eclipse.org/projects/project-plan.php?planurl=https://www.eclipse.org/eclipse/development/plans/eclipse_project_plan_4_25.xml but updated for 4.26.

In this folder: https://github.com/eclipse-platform/www.eclipse.org-eclipse/tree/master/development/plans there is no file eclipse_project_plan_4_26.xml

**Comment by akurtakov** [comment]
Were you looking for some specific information on this page ?

**Comment by pstric** [comment]
Thank you for updating the page.

I was looking for the projected release date for the next milestone.

Until a couple of years ago, I would usually go to "The Eclipse Project Downloads" at https://download.eclipse.org/eclipse/downloads/ and click on the link [Eclipse Project](https://www.eclipse.org/eclipse/) in the first paragraph. From here I would click on the link "Eclipse Project Development" (the first bullet point) and reach the Eclipse Project Plan for the net upcoming release.

This was an easy way to find out when I could expect the first milestone of the next version of Eclipse. Sadly this link got broken some years ago, and https://www.eclipse.org/eclipse/development/ now redirects to https://projects.eclipse.org/projects/eclipse.platform which is based on the generic template for Eclipse Projects. This page does not give me the info I am looking for (projected release dates for milestones RCs and GA). I would be very happy to see this link also restored.

**Comment by akurtakov** [comment]
Do you say fixing Development link to point to project plan is what  you look for ?

**Comment by pstric** [comment]
Yes, that would be very nice. Thank you.

**Comment by akurtakov** [comment]
I thought more about it but this would require editing this file for each release which I'm not ready to do. For this release I added the milestones/rcs info on https://projects.eclipse.org/projects/eclipse/releases/4.26.0 but we are reducing this kind of work on each release as there is just not enough time for it. Help is always more than welcome.

**Comment by merks** [comment]
@pstric 

Note that this has a schedule on which the platform's schedule is based:

https://wiki.eclipse.org/Category:SimRel-2022-12

The platform is of +0 which is today for M2...
