### ISSUE TITLE
Reopen the previous closed tab 

### ISSUE THREAD

**Issue by DDanny1999** [eclipse-platform/www.eclipse.org-eclipse#196]
Let's make sure issue is not already fixed in latest builds first.

- [x] I verified [latest Integration Build of Eclipse SDK](https://download.eclipse.org/eclipse/downloads/) doesn't provide the feature.

## Suggestion

I would like to be able to reopen a closed tab in Eclipse View. You might know this feature already from Browser like Firefox or Edge. If you right click in the tab-bar of the browser you have the following options:

![grafik](https://github.com/user-attachments/assets/fa291bce-dc7c-4360-951f-e99aa0093b94)

I would love to have something similar in ADT. I think it would provide a better usability.

![grafik](https://github.com/user-attachments/assets/950fc659-1efe-4581-a188-8d5fe99a2193)

## Community

- [x] I understand suggesting an enhancement doesn't mandate anyone to implement it. Other contributors may consider this suggestion, or not, at their own convenience. The most efficient way to get it fixed is that I implement it myself and contribute it back as a good quality patch to the project.

**Comment by DDanny1999** [comment]
Verification of the boxes

**Comment by HannesWell** [comment]
Unfortunately this is not the right place for this issue. A suitable place should be https://github.com/eclipse-platform/eclipse.platform.ui/issues

> I would love to have something similar in ADT. I think it would provide a better usability.

It looks like you are using the ABAP Development tools from SAP? Therefore it might also be an option for you to report it directly to SAP? @BeckerWdf can you advice?

**Comment by merks** [comment]
Note that it is possible to transfer issues to repos in the same GitHub organization as in the case. 

I think the File menu’s open recent list is similar to what you want, isn’t it?

**Comment by DDanny1999** [comment]
Oh I didn't know about that functionality. I just copy & pasted the issue into a new issue. I can delete it again and then move this to the right place. 
Should I proceed with that?

**Comment by merks** [comment]
No it’s not a problem that you didn’t move the issue. I just wanted @HannesWell to be aware of that for future reference.  😄

**Comment by DDanny1999** [comment]
Ok! Thank you very much.

And you are right. I want something similar to that "File menu's open recent list".

**Comment by HannesWell** [comment]
> No it’s not a problem that you didn’t move the issue. I just wanted @HannesWell to be aware of that for future reference.  😄 

You are right. Sorry, I just forget that in this situation respectively I didn't consider both repos are in the org. 😅
