### ISSUE TITLE
Complete N&N for 4.33

### ISSUE THREAD

**Issue by merks** [eclipse-platform/www.eclipse.org-eclipse#211]
New and noteworthy affects all projects:

  https://eclipse.dev/eclipse/news/4.33/

though the content is maintained here in one project:

https://github.com/eclipse-platform/www.eclipse.org-eclipse/tree/master/news/4.33

In any case, before the release, I've been cleaning up empty sections, e.g.,

https://eclipse.dev/eclipse/news/4.33/jdt.php
https://eclipse.dev/eclipse/news/4.33/pde.php

and removing references to entirely empty pages, e.g.,

https://eclipse.dev/eclipse/news/4.33/platform_isv.php

But then I discovered that the content is copied to doc plugins at some point, which must be very soon now to be in RC2, e.g.,

![image](https://github.com/user-attachments/assets/ef2bd6ad-a200-4a5d-a2ab-cc0f83a951aa)

So are we really done with the N&N for this cycle so that I can do the cleanup? Is there nothing else interesting that was done in JDT?  Are there really no new APIs in the Platform or Equinox?

**Comment by akurtakov** [comment]
Please don't wait for adding N&N items at end of cycle but rather write it down as soon as it's in I-build. 
Also don't hesitate to add N&N for smaller items as this is what users read/see for releases.

**Comment by BeckerWdf** [comment]
> o are we really done with the N&N for this cycle so that I can do the cleanup?

@Christopher-Hermann would like to add an entry for the "Sticky Scrolling" feature. Is that still possible? I also wondering because of https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/pull/2248.

**Comment by akurtakov** [comment]
@BeckerWdf you have by EOD tomorrow, waiting for last minute is not nice from releng POV as even fixing a typo will require respins!

**Comment by merks** [comment]
Yes, this copying process is a problem because I don't know when exactly it happens.  Somehow the cleanup  of empty sections/pages needs to be synced and finished before the copying process or along with the copying process.  

Also all the developers need to be aware that at some point there are two copies of everything, hence @akurtakov comment about doing this as soon as it's new.

**Comment by akurtakov** [comment]
IMO it's time to stop copying N&N in docs bundles and point to online content instead.

**Comment by Christopher-Hermann** [comment]
I added the sticky scrolling feature to the N&N via #212. Sorry for the late input, I didn't had time the last weeks due to vacation time.

**Comment by merks** [comment]
Oh dear, yes that is of fundamental interest/import!

**Comment by trancexpress** [comment]
> I'm still on vacation, I believe we miss the entry about dropping support for old Java targets in compiler. Would be good to have some note in N&N. I will be able to do this tomorrow afternoon (I hope). If someone could do it before, please do. @trancexpress ?

@iloveeclipse  is this enough?

![image](https://github.com/user-attachments/assets/fb23e367-6111-4e1d-b851-1176c37b8564)

**Comment by merks** [comment]
Small nits.  

`I.e.` is **always** followed by a comma, i.e., `i.e.,`. 

The last sentence should probably mention `javac` rather than just mention `Java 21`, e.g., this is equivalent to Java 21's javac only supporting...

In any case, thanks for the rapid response. 🚀 ❤️

**Comment by HannesWell** [comment]
> IMO it's time to stop copying N&N in docs bundles and point to online content instead.

In my opinion the opposite is also an option worth to consider:
Maintain the news in the doc-bundles at the corresponding repositories (using Markdown syntax 😃) and automatically copy the content to the website on a change. This would avoid the need to contribute to (and point newcomers) to yet another repository.

> Please don't wait for adding N&N items at end of cycle but rather write it down as soon as it's in I-build. Also don't hesitate to add N&N for smaller items as this is what users read/see for releases.

If the doc-bundle in the PDE/JDT/Platform repo is the master, one could add the N&N entry with the feature in one commit (if it's in the same repo).

**Comment by HannesWell** [comment]
> So are we really done with the N&N for this cycle so that I can do the cleanup? Is there nothing else interesting that was done in JDT? Are there really no new APIs in the Platform or Equinox?

From the top of my head I remember the new APIs in IFile from @jukzi in
- https://github.com/eclipse-platform/eclipse.platform/pull/1397
- https://github.com/eclipse-platform/eclipse.platform/pull/1420
- https://github.com/eclipse-platform/eclipse.platform/pull/1436

etc. IMO it would be good to add an entry for them.

**Comment by merks** [comment]
The SWT APIs section is empty:

https://github.com/eclipse-platform/www.eclipse.org-eclipse/blob/326fcd5cda6e92ab49f44f267b196a8936d90a6c/news/4.33/platform_isv.html#L61-L64

But my search indicates that's maybe an oversight.

![image](https://github.com/user-attachments/assets/3c0f3eb6-6dde-4db6-9729-06df03733036)

@laeubi 

Surely given the time we spent discussing and tuning `BusyIndicator.showWhile(Future<?>)` it calls for a note.

@HeikoKlare 

The display changes aren't worth calling attention to at this time?

**Comment by HeikoKlare** [comment]
@merks thank you for pointing to those changes.

> The display changes aren't worth calling attention to at this time?

Exactly. These changes are for enabling/evaluating the multi-monitor HiDPI support (rescaling at runtime) on Windows. However, the feature is still work-in-progress, so I would prefer to not emphasize these API extensions now. We expect the feature to become ready for production during 2024-12 development, which is why I propose to promote the according API for that release.
One might argue that the API was technically introduced with 2024-09, so promoting it for 2024-12 is kind of "inconsistent", but I do not see a benefit in promoting a kind of experimental API now while it becomes really useful with the next release (and will thus worth to be mentioned in the N&N for 2024-12).

**Comment by merks** [comment]
Folks added a bunch of N&N entries and finally now I've commented out empty sections.
