### ISSUE TITLE
Download for 2024-09 (4.33.0) does not show sha512 hash

### ISSUE THREAD

**Issue by JanMosigItemis** [eclipse-platform/www.eclipse.org-eclipse#225]
- [x] I verified I can reproduce this issue against [20240905-0614](https://download.eclipse.org/eclipse/downloads/)

## Steps to reproduce

Go to https://www.eclipse.org/downloads/download.php?file=/technology/epp/downloads/release/2024-09/R/eclipse-java-2024-09-R-win32-x86_64.zip and click the "SHA-512" button.

I expected: sha512 hash code of the file.

But got: Unable to locate sums for this file (3120).

## Tested under this environment:
* OS & Version: Microsoft Windows [Version 10.0.22621.4037] (Windows 11)
* Chrome 128.0.6613.138
* Eclipse IDE / Platform version: 20240905-0614

## Community

- [x] I understand reporting an issue to this OSS project does not mandate anyone to fix it. Other contributors may consider the issue, or not, at their own convenience. The most efficient way to get it fixed is that I fix it myself and contribute it back as a good quality patch to the project.

**Comment by mickaelistria** [comment]
Yes, it does as per URL (`technology/epp`).
@JanMosigItemis this issue is not about Eclipse Platform, please report it to the Eclipse Packaging Project https://github.com/eclipse-packaging/packages/

**Comment by merks** [comment]
Does the SHA value you get from the link look the same as the corresponding one in the folder?

https://download.eclipse.org/justj/?file=/technology/epp/downloads/release/2024-09/R/

I think (but am not sure) the SHA from the button comes from the server and isn't the one project provides directly...

**Comment by JanMosigItemis** [comment]
Thanks @mickaelistria, will do 👍

@merks not sure what you mean. The button does not reveal any hash code. However, I checked the hash provided by https://download.eclipse.org/technology/epp/downloads/release/2024-09/R/eclipse-java-2024-09-R-win32-x86_64.zip.sha512 against my "local" hash and they do match.

FYI we'll continue here --> https://github.com/eclipse-packaging/packages/issues/211

**Comment by merks** [comment]
Yes, sorry, I see that now.  I'm asking the webmaster about it as I type...

**Comment by jonahgraham** [comment]
Thanks for moving to EPP - for what it is worth the issue is not EPP specific and affects Platform and everyone else too. See IT helpdesk entry: https://gitlab.eclipse.org/eclipsefdn/helpdesk/-/issues/5011
