### ISSUE TITLE
Nebula download page out of date

### ISSUE THREAD

**Issue by tito-cu** [eclipse-platform/www.eclipse.org-eclipse#63]
From https://projects.eclipse.org/projects/technology.nebula when trying to download the latest Nebula widgets version (https://projects.eclipse.org/projects/technology.nebula/downloads), the page redirects to https://eclipse.dev/nebula/downloads.php which is out of date as the latest released Nebula version is 3.0.0. and not 2.7.2 like the page states (source: https://github.com/eclipse/nebula/releases)

**Comment by merks** [comment]
This sounds like something you should report to Nebula:

https://projects.eclipse.org/projects/technology.nebula/developer
