### ISSUE TITLE
4.25 Project plan

### ISSUE THREAD

**Issue by sravanlakkimsetti** [eclipse-platform/www.eclipse.org-eclipse#9]
Need a project plan for 4.25 when we start work on master on Jun 3, 2022

Notifications:
@lshanmug

**Comment by lshanmug** [comment]
GitHub links/query for plan issues yet to be added to the plan. Keeping issue open.

**Comment by vogella** [comment]
@akurtakov do we still need the plan issues? Feels like they not adding a lot of value, I used to maintain them in detail for platform but stopped as nobody seemed to use them except me.

**Comment by akurtakov** [comment]
They are nice to have but I have to admit that since we more and more depend on people not working on Eclipse full time planning is close to impossible as we have no idea what will be contributed for given resource, I no longer try to plan features for given release. This is a not a problem as it shows bigger diversity in contributors which is good for the long term viability of the project but it makes some of the things we used to do not so relevant anymore.

**Comment by vogella** [comment]
@lshanmug @jarthana  are these plan items valuable to your team?

**Comment by sravanlakkimsetti** [comment]
> GitHub links/query for plan issues yet to be added to the plan. Keeping issue open.

I already sent this to platfom-dev sometime back. Here are the queries

Platform: https://github.com/issues?q=is%3Aissue+org%3Aeclipse-platform+label%3Aplan+milestone%3A4.25
Equinox: https://github.com/issues?q=is%3Aissue+org%3Aeclipse-equinox+label%3Aplan+milestone%3A4.25
PDE      : https://github.com/issues?q=is%3Aissue+org%3Aeclipse-pde+label%3Aplan+milestone%3A4.25
JDT       : https://github.com/issues?q=is%3Aissue+org%3Aeclipse-jdt+label%3Aplan+milestone%3A4.25

**Comment by lshanmug** [comment]
> @lshanmug @jarthana are these plan items valuable to your team?

We use plan items to track a feature and it's associated work.
In bugzilla, we used to create top level bug for a feature and mark it as plan item and then create dependent bugs for the feature work. In GitHub, need to check how to do it.

**Comment by lshanmug** [comment]
> > GitHub links/query for plan issues yet to be added to the plan. Keeping issue open.
> 
> I already sent this to platfom-dev sometime back. Here are the queries
> 
> Platform: https://github.com/issues?q=is%3Aissue+org%3Aeclipse-platform+label%3Aplan+milestone%3A4.25 Equinox: https://github.com/issues?q=is%3Aissue+org%3Aeclipse-equinox+label%3Aplan+milestone%3A4.25 PDE : https://github.com/issues?q=is%3Aissue+org%3Aeclipse-pde+label%3Aplan+milestone%3A4.25 JDT : https://github.com/issues?q=is%3Aissue+org%3Aeclipse-jdt+label%3Aplan+milestone%3A4.25

Thanks, tried that, but it doesn't include all milestones, such as 4.25, 4.25M1, etc. For example, this link doesn't show 4.24 plan items as the milestone is set to 4.24M1, https://github.com/issues?q=is%3Aissue+org%3Aeclipse-platform+label%3Aplan+milestone%3A4.24 
Also, I tried the links in the plan page locally and they gave 404 error. But, not in the browser. Not sure why.

**Comment by sravanlakkimsetti** [comment]
> > > GitHub links/query for plan issues yet to be added to the plan. Keeping issue open.
> > 
> > 
> > I already sent this to platfom-dev sometime back. Here are the queries
> > Platform: https://github.com/issues?q=is%3Aissue+org%3Aeclipse-platform+label%3Aplan+milestone%3A4.25 Equinox: https://github.com/issues?q=is%3Aissue+org%3Aeclipse-equinox+label%3Aplan+milestone%3A4.25 PDE : https://github.com/issues?q=is%3Aissue+org%3Aeclipse-pde+label%3Aplan+milestone%3A4.25 JDT : https://github.com/issues?q=is%3Aissue+org%3Aeclipse-jdt+label%3Aplan+milestone%3A4.25
> 
> Thanks, tried that, but it doesn't include all milestones, such as 4.25, 4.25M1, etc. For example, this link doesn't show 4.24 plan items as the milestone is set to 4.24M1, https://github.com/issues?q=is%3Aissue+org%3Aeclipse-platform+label%3Aplan+milestone%3A4.24 Also, I tried the links in the plan page locally and they gave 404 error. But, not in the browser. Not sure why.

The query works per milestone only. You'll need to target all plan bugs to release

**Comment by lshanmug** [comment]
The issue was reopened to add the plan items query, it's no longer required as per https://github.com/eclipse-platform/www.eclipse.org-eclipse/pull/11, so closing. The section can be removed in a separate PR.
