### ISSUE TITLE
Broken link in platform_whatsnew.html

### ISSUE THREAD

**Issue by alshamams** [eclipse-platform/www.eclipse.org-eclipse#96]
Let's make sure issue is not already fixed in latest builds first.

- [x] I verified I can reproduce this issue against [latest Integration Build of Eclipse SDK](https://download.eclipse.org/eclipse/downloads/)

## Steps to reproduce

From a fresh installation and clean workspace:

https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/blob/7adbea1b0de4b35b6a252dbb8e31e8fa4e262048/eclipse.platform.common/bundles/org.eclipse.platform.doc.user/whatsNew/platform_whatsnew.html#L94

The above link is broken. Should it be https://eclipse.dev/eclipse/news/4.28/platform.php#Security ?

https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/blob/7adbea1b0de4b35b6a252dbb8e31e8fa4e262048/eclipse.platform.common/bundles/org.eclipse.platform.doc.user/whatsNew/platform_whatsnew.html#L41

The above link is leading to an empty page. Should it be PDE's whatsnew?

## Here is some relevant log output

https://download.eclipse.org/eclipse/downloads/drops4/I20231122-0600/testresults/html/org.eclipse.ua.tests.doc_ep430I-unit-mac64-java17_macosx.cocoa.x86_64_17.html

## Community

- [x] I understand reporting an issue to this OSS project does not mandate anyone to fix it. Other contributors may consider the issue, or not, at their own convenience. The most efficient way to get it fixed is that I fix it myself and contribute it back as a good quality patch to the project.

@merks

**Comment by merks** [comment]
@iloveeclipse 

Sorry, I lost track of the issue/PR where this problem was being discussed.

**Comment by alshamams** [comment]
All right, no problem. Let me go ahead with the proposed edits.
