### ISSUE TITLE
get rid of plugin copies

### ISSUE THREAD

**Issue by jukzi** [eclipse-platform/www.eclipse.org-eclipse#99]
there are some java files in this repository which seem to be an outdated copy of other platform repositories
see
https://github.com/eclipse-platform/www.eclipse.org-eclipse/blob/master/platform-ui/plugins/readme.txt
https://github.com/eclipse-platform/www.eclipse.org-eclipse/blob/master/platform-core/plugins/readme.txt

idea is to delete:

platform-ui/plugins
platform-core/plugins

because it is irritating to have for example two MarkerProblemSeverityAndMessageField.java in workspace

**Comment by akurtakov** [comment]
Please go in small chunks here. If smth is in regular repos remove it first with clear pointer to where the actual code is in the  other repo.
I assume there are some links to these projects on the webpage - please search for it and fix/remove when deleting too.

**Comment by akurtakov** [comment]
Do you plan more work here or this one should be closed?
